import test from 'node:test';import assert from 'node:assert/strict';
import {chartQuantity,FUEL_COLOURS,sourceIndicator} from '../src/lib/atlasPresentation.mjs';
import {ATLAS_DEFAULTS,atlasSearch,readAtlasState} from '../src/lib/atlasState.mjs';
import {assetView} from '../src/lib/assetExplorer.mjs';
test('explicit dimensional contract: 2000MW is 2GW; 2000MWh is 2GWh, not integrated by the tooltip',()=>{assert.equal(chartQuantity(2000,'power'),'2.0 GW');assert.equal(chartQuantity(2000,'energy'),'2.0 GWh');assert.equal(chartQuantity(-300,'power'),'-0.3 GW');assert.equal(chartQuantity(0,'energy'),'0.0 GWh');assert.equal(chartQuantity(null,'power'),'Unavailable');assert.equal(chartQuantity(NaN,'energy'),'Unavailable');assert.throws(()=>chartQuantity(2000,'watts'));});
test('freshness never signals live from a missing, failed or future source',()=>{const now=Date.parse('2026-09-27T18:30:00Z');assert.equal(sourceIndicator({timestamp:'2026-09-27T18:25:00Z',now,cadenceMinutes:5}).state,'current');assert.equal(sourceIndicator({timestamp:'2026-09-27T18:25:00Z',now,failed:true}).state,'retained');assert.equal(sourceIndicator({timestamp:'2026-09-27T18:00:00Z',now,cadenceMinutes:5}).state,'delayed');assert.equal(sourceIndicator({timestamp:'2026-09-27T18:31:00Z',now}).state,'unavailable');assert.equal(sourceIndicator({timestamp:null,now}).fresh,false)});
test('same fuel family has a shared semantic colour across map and chart',()=>{assert.equal(FUEL_COLOURS.Wind,FUEL_COLOURS['Offshore wind']);assert.equal(FUEL_COLOURS.Wind,FUEL_COLOURS['Onshore wind']);assert.equal(FUEL_COLOURS.PSH,FUEL_COLOURS['Pumped storage'])});
test('atlas URL round trip preserves filters, selection, query and camera without discarding campaign params',()=>{const state={...ATLAS_DEFAULTS,assetSearch:'Drax',assetCountry:'England',minCapacity:100,selected:'drax',panel:'detail',expanded:true,viewport:assetView(400,420,3)};const url=atlasSearch(state,'?utm_source=test');assert.match(url,/utm_source=test/);assert.deepEqual(readAtlasState(url),state);assert.equal(readAtlasState('?asset=drax').selected,'drax')});
test('untrusted URL limits and defaults do not create a broken camera',()=>{const s=readAtlasState('?layer=garbage&capacity=-1&camera=NaN,0,999');assert.equal(s.mode,'generation');assert.equal(s.minCapacity,0);assert.deepEqual(s.viewport,ATLAS_DEFAULTS.viewport);assert.equal(readAtlasState('?camera=400,400,100').viewport.zoom,32)});
