import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {numberOrNull,londonTime,normalizeBoundaries,boundarySummary,changesEvidence,halfHours,DOMESTIC,INTERCONNECTORS,sourceHealth} from '../src/lib/evidence/calculations.mjs';
const now=Date.parse('2026-09-18T12:00Z');
function fixture(){const fuels=[],demand=[];for(const [i,from] of ['2026-09-18T10:00:00Z','2026-09-18T10:30:00Z'].entries()){const common={startTime:from,publishTime:new Date(Date.parse(from)+1800000).toISOString()};for(const code of [...DOMESTIC,...INTERCONNECTORS,'PS'])fuels.push({...common,fuelType:code,generation:code==='WIND'?1000+i*100:code==='INTFR'?-100:code.startsWith('INT')?10:code==='PS'?-200:20});demand.push({...common,demand:10000+i*200})}return {fuels,demand}}
test('missing and nonnumeric are not zero',()=>{for(const v of [null,undefined,'',' ','NaN',NaN,'n/a'])assert.equal(numberOrNull(v),null);assert.equal(numberOrNull('0'),0);assert.equal(numberOrNull('-12.5'),-12.5)});
test('London local time handles BST, rejects repeated and nonexistent clock-change times',()=>{assert.equal(londonTime('2026-09-18T12:00:00'),'2026-09-18T11:00:00.000Z');assert.equal(londonTime('2026-01-18T12:00:00'),'2026-01-18T12:00:00.000Z');assert.equal(londonTime('2026-10-25T01:30:00'),null);assert.equal(londonTime('2026-03-29T01:30:00'),null)});
test('conflicting NESO rows are unavailable rather than guessed revisions',()=>{const r={'Constraint Group':'X','Date_ Time GMT_BST':'2026-09-18T14:00:00',Flow_MW:10,Limit_MW:100};const rows=normalizeBoundaries([r,{...r,Flow_MW:20}]);assert.equal(rows.length,1);assert.equal(rows[0].flowMW,null)});
test('expired forecast is not live and negative direction is not absolute loading',()=>{const past={boundary:'X',from:'2026-09-18T10:00Z',flowMW:200,limitMW:100};assert.deepEqual(boundarySummary([past],now),[]);const s=boundarySummary([{...past,from:'2026-09-18T13:00Z',flowMW:-200}],now);assert.equal(s[0].gapMW,300)});
test('MW stays MW, NI remains external, storage and embedded estimates do not enter domestic totals',()=>{const {fuels,demand}=fixture();fuels.push({...fuels[0],fuelType:'SOLAR',generation:9999});const r=halfHours(fuels,demand,now)[0];assert.equal(r.windMW,1000);assert.equal(r.demandMW,10000);assert.equal(r.generationMW,1160);assert.equal(r.renewableMW,1040);assert.equal(r.storageMW,-200);assert.equal(r.netImportsMW,-10)});
test('every cable is required; missing export never turns into a balanced zero',()=>{const {fuels,demand}=fixture();const r=halfHours(fuels.filter(r=>r.fuelType!=='INTIRL'),demand,now);assert.equal(r[0].netImportsMW,null)});
test('latest published revision wins; future publication is excluded',()=>{const {fuels,demand}=fixture();fuels.push({...fuels.find(r=>r.fuelType==='WIND'),generation:1100,publishTime:'2026-09-18T11:00Z'});fuels.push({...fuels.find(r=>r.fuelType==='WIND'),generation:9999,publishTime:'2026-09-19T11:00Z'});assert.equal(halfHours(fuels,demand,now)[0].windMW,1100)});
test('only adjacent completed periods create changes',()=>{const {fuels,demand}=fixture();const result=changesEvidence(fuels,demand,now);assert.equal(result.rows.find(r=>r.key==='windMW').delta,100);assert.equal(result.rows.find(r=>r.key==='demandMW').delta,200);assert.equal(changesEvidence(fuels.filter(r=>r.startTime.endsWith('10:00:00Z')),demand,now),null)});
test('missing demand suppresses only that comparison, not inventing demand from generation',()=>{const {fuels}=fixture();assert.equal(changesEvidence(fuels,[],now).rows.find(r=>r.key==='demandMW').delta,null)});
test('failure retains a visibly failed source state even if recently checked',()=>assert.match(sourceHealth({checkedAt:'2026-09-18T11:59Z',error:'offline'},now),/failed/));
test('canonical reviewed selection preserves source IDs and excludes retired Drax units',()=>{const a=JSON.parse(fs.readFileSync(new URL('../src/data/atlas/canonical-assets.json',import.meta.url)));const pilot=a.filter(r=>r.releaseSelection);assert.equal(pilot.length,6);assert.equal(new Set(a.map(r=>r.canonicalId)).size,a.length);for(const r of pilot){assert.equal(r.unitMatch.status,'verified');assert.ok(r.sourceRefs.length);if(r.type.includes('wind'))assert.ok(r.sourceRefs.some(s=>s.provider==='DESNZ REPD'));}assert.ok(!pilot.find(r=>r.id==='drax').units.includes('T_DRAXX-5'));assert.equal(a.find(r=>r.id==='seagreen').unitMatch.status,'ambiguous')});
