import {test} from 'node:test';import assert from 'node:assert/strict';
import {dayBounds,elexonDay,nesoDay,validateDay,summarizeDays,carbonDay,FUELS} from '../src/lib/evidence/reportValidation.mjs';
function fixture(date='2026-09-28',basis='UTC'){const b=dayBounds(date,basis);const e=[],n=[];for(let i=0;i<b.count;i++){const from=new Date(Date.parse(b.from)+i*1800000).toISOString();for(const fuelType of FUELS)e.push({startTime:from,publishTime:new Date(Date.parse(from)+1800000).toISOString(),fuelType,generation:fuelType==='PS'?-20:100});n.push({DATETIME:from,GAS:200,WIND:100,NUCLEAR:100,BIOMASS:100,HYDRO:100,SOLAR:100});}const hours=b.count/2;const f={Gas:200,Wind:100,Nuclear:100,Biomass:100,Hydro:100,Coal:100,Other:200,Solar:100};const row={settlementDate:date,timeBasis:basis,totalPeriods:b.count,totalMW:1000*hours,fuelMix:Object.entries(f).map(([fuelType,mw])=>({fuelType,mw:mw*hours}))};return {b,e,n,row};}
test('complete data reconciles all intervals, energy and signed storage',()=>{const f=fixture(),v=validateDay(f.row,f.e,f.n);assert.equal(v.status,'passed');assert.equal(v.recalculated.signedStorageMWh,-480);assert.equal(v.recalculated.renewableMWh,7200);});
test('DST days use 46 and 50 periods, not assumed 48',()=>{for(const [date,count]of [['2026-03-29',46],['2026-10-25',50]]){const f=fixture(date,'Europe/London');assert.equal(f.b.count,count);assert.equal(validateDay(f.row,f.e,f.n).status,'passed');}});
test('missing fuel and null values fail, zero stays valid',()=>{const f=fixture();assert.ok(elexonDay(f.e.slice(1),f.b).errors.length);f.e[0].generation=null;assert.ok(elexonDay(f.e,f.b).errors.length);f.e[0].generation=0;assert.equal(elexonDay(f.e,f.b).errors.length,0);});
test('newest revision wins regardless of order; conflicting same revision fails',()=>{const f=fixture(),revision={...f.e[0],generation:123,publishTime:'2026-09-29T00:00Z'};assert.equal(elexonDay([revision,...f.e],f.b).periods[0].values.BIOMASS,123);assert.ok(elexonDay([...f.e,{...f.e[0],generation:120}],f.b).errors.length);});
test('NESO duplicate and absent slots fail even if record count matches',()=>{const f=fixture();f.n[1]=f.n[0];assert.ok(nesoDay(f.n,f.b).errors.length);});
test('pumped storage cannot be counted as natural hydro',()=>{const f=fixture();f.row.fuelMix.find(x=>x.fuelType==='Hydro').mw+=500;assert.equal(validateDay(f.row,f.e,f.n).checks.find(c=>c.id==='report.fuel.Hydro').status,'fail');});
test('one provider interval disagreement fails even when averages cancel',()=>{const f=fixture();f.n[0].WIND+=100;f.n[1].WIND-=100;assert.equal(validateDay(f.row,f.e,f.n).checks.find(c=>c.id==='cross-source.WIND').status,'fail');});
test('period shares and power are energy/hour weighted; partial range warned',()=>{const days=[{status:'passed',bounds:{count:46},recalculated:{totalMWh:100,renewableMWh:100}},{status:'passed',bounds:{count:50},recalculated:{totalMWh:900,renewableMWh:0}}];const s=summarizeDays(days);assert.equal(s.renewableShare,10);assert.equal(s.averageMW,1000/48);assert.equal(s.status,'warning');});
test('carbon uses actuals only and never fills gaps with forecasts',()=>{const f=fixture();const r=f.n.map(n=>({from:n.DATETIME,to:new Date(Date.parse(n.DATETIME)+1800000).toISOString(),intensity:{actual:0,forecast:100}}));assert.equal(carbonDay(r,f.b).meanActualGCO2PerKWh,0);r[0].intensity.actual=null;assert.equal(carbonDay(r,f.b).status,'unavailable');});
import {validateReportAllDays} from '../scripts/validate-report-all-days.mjs';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
test('end-to-end evidence pack fails closed and retains report input',async()=>{
 const f=fixture();f.row.fuelMix.find(x=>x.fuelType==='Hydro').mw+=500;const dir=mkdtempSync(join(tmpdir(),'report-validation-'));
 const fetcher=async url=>({ok:true,text:async()=>JSON.stringify(url.includes('limit=1')?{success:true,result:{fields:[{id:'DATETIME',info:{description:'UTC'}}]}}:url.includes('elexon')?{data:f.e}:url.includes('neso')?{success:true,result:{records:f.n}}:{data:[]})});
 try{const v=await validateReportAllDays([f.row],{outRoot:dir,reportDate:'2026-09-29',fetcher});assert.equal(v.status,'failed');assert.equal(v.days[0].carbon.status,'unavailable');assert.ok(v.artifacts.every(a=>a.sha256.length===64));assert.ok(v.evidencePath.endsWith('/manifest.json'));}finally{rmSync(dir,{recursive:true});}
});
test('date gaps and mixed day bases block the run',async()=>{const f=fixture(),g={...f.row,settlementDate:'2026-09-30'};await assert.rejects(validateReportAllDays([f.row,g]),/Missing day/);g.settlementDate='2026-09-29';g.timeBasis='Europe/London';await assert.rejects(validateReportAllDays([f.row,g]),/Mixed/);});
