import {useState} from 'react';import {Helmet} from 'react-helmet-async';
import {useGridEvidence,type EvidenceSource} from '@/hooks/useGridEvidence';
import {boundarySummary,sourceHealth,numberOrNull} from '@/lib/evidence/calculations.mjs';
import {evidenceTime} from '@/components/GridEvidenceBriefing';
import '@/styles/grid-evidence.css';
const display=(v:unknown)=>{const n=numberOrNull(v);return n===null?'Unavailable':n.toLocaleString('en-GB',{maximumFractionDigits:0})};
function Source({source}:{source?:EvidenceSource}){return <details className="evidence-source"><summary>Source, freshness and revision</summary>{source?<><p>{source.provider} · {source.kind} · {source.unit} · {source.coverage}</p><p>{sourceHealth(source)}. Checked {evidenceTime(source.checkedAt)} UK; provider resource modified {evidenceTime(source.resourceModifiedAt)} UK. Row publication time: {evidenceTime(source.publishedAt)}. Resource modification is not an observation or row publication time.</p><p>Provider schedule: {source.providerSchedule}. Revision <code>{source.revision}</code></p><a href={source.url}>Official source ↗</a> · <a href={source.licence}>Licence ↗</a>{source.error&&<p>Last refresh failed; retained data keeps its original timestamps.</p>}</>:<p>Source unavailable.</p>}</details>}
export default function NetworkConstraints(){
 const feed=useGridEvidence(),sources=feed.data?.sources;const [tab,setTab]=useState<'dayAhead'|'congestion'|'costs'>('dayAhead');const [selected,setSelected]=useState('');const source=sources?.[tab];const summaries=boundarySummary(sources?.dayAhead?.records||[]);const chosen=selected||summaries[0]?.boundary||'';
 const day=(sources?.dayAhead?.records||[]).filter(r=>r.boundary===chosen&&typeof r.from==='string'&&Date.parse(r.from)>=Date.now()&&Date.parse(r.from)<=Date.now()+48*3600000);
 const max=Math.max(1,...day.flatMap(r=>[Math.abs(numberOrNull(r.flowMW)||0),numberOrNull(r.limitMW)||0]));
 const latestCost=(sources?.costs?.records||[]).map(r=>String(r['Settlement Date'])).sort().at(-1);const costs=(sources?.costs?.records||[]).filter(r=>r['Settlement Date']===latestCost);
 return <main className="network-evidence"><Helmet><title>GB network constraints — forecasts, limits and costs | Energy Mix</title><meta name="description" content="Official NESO day-ahead boundary forecasts, published network limits and historical thermal constraint costs, clearly distinguished and sourced."/><link rel="canonical" href="https://energymix.info/network-constraints/"/></Helmet><p className="atlas-eyebrow">NETWORK / ENGLAND · SCOTLAND · WALES</p><h1>Power has to get there.</h1><p className="evidence-lead">Generation is only part of the story. The network has limits—and different datasets describe different moments.</p>
 <div className="evidence-tabs" role="group" aria-label="Constraint evidence type">{([['dayAhead','Day-ahead forecasts'],['congestion','Published boundary limits'],['costs','Retrospective costs']] as const).map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {(feed.isError||source?.error)&&<p className="evidence-warning" role="status">Refresh unavailable. Any retained evidence remains dated; this is not live operational telemetry.</p>}
 {tab==='dayAhead'&&<section><p className="evidence-badge">FORECAST · MW</p><h2>Day-ahead boundary flows and limits</h2><p>NESO models flows from forecasts of demand, wind and dispatch. Limits belong to the same published snapshot, not a permanent rating. Positive direction follows NESO’s diagrams. A forecast exceedance is not a measured breach or proof of curtailment.</p>{summaries.length?<><label>Boundary <select value={chosen} onChange={e=>setSelected(e.target.value)}>{summaries.map(r=><option key={r.boundary}>{r.boundary}</option>)}</select></label><div className="evidence-chart"><svg viewBox="0 0 700 160" role="img" aria-label={`${chosen} forecast flow and published limit; exact readings follow in the table`}><line x1="10" y1="80" x2="690" y2="80" stroke="#365369"/>{day.map((r,i)=>{const x=10+i/Math.max(1,day.length-1)*680;const flow=numberOrNull(r.flowMW),limit=numberOrNull(r.limitMW);return <g key={String(r.from)}>{flow!==null&&<line x1={x} x2={x} y1="80" y2={80-flow/max*65} stroke="#49d8e6" strokeWidth="3"/>}{limit!==null&&<circle cx={x} cy={80-limit/max*65} r="2" fill="#f0c471"/>}</g>})}</svg><p>Cyan: signed forecast flow · amber: published limit · chronological half-hours, read exact times below.</p></div><div className="evidence-scroll"><table><thead><tr><th>Valid from (UK)</th><th>Forecast flow MW</th><th>Published limit MW</th><th>Limit minus flow MW</th></tr></thead><tbody>{day.map(r=><tr key={String(r.from)}><th>{evidenceTime(String(r.from))}</th><td>{display(r.flowMW)}</td><td>{display(r.limitMW)}</td><td>{numberOrNull(r.flowMW)!==null&&numberOrNull(r.limitMW)!==null?display(Number(r.limitMW)-Number(r.flowMW)):'Unavailable'}</td></tr>)}</tbody></table></div></>:<p role="status">No upcoming periods within 48 hours are available. An expired forecast is not relabelled live.</p>}<p><a href="https://api.neso.energy/dataset/cf3cbc92-2d5d-4c2b-bd29-e11a21070b26/resource/3eb74046-3ffa-40c3-a541-b3cb00a44b1f/download/scotland-network-diagram-da-limit-boundaries2026.pdf">NESO Scotland boundary diagram ↗</a> · <a href="https://api.neso.energy/dataset/cf3cbc92-2d5d-4c2b-bd29-e11a21070b26/resource/bb6d6ec6-16d9-4be5-b32c-1a70c09fd871/download/ew-network-diagram-da-limit-boundaries2026.pdf">England & Wales diagram ↗</a></p></section>}
 {tab==='congestion'&&<section><p className="evidence-badge">PUBLISHED LIMITS · MW · WEEKLY</p><h2>Network congestion update</h2><p>NESO’s Operational Transparency Forum publishes weekly boundary capability. “Actual” below means a historical limit—not measured flow. Forecast limits are separate. Boundary names are retained as published and are not guessed to match another dataset’s codes.</p><div className="evidence-scroll"><table><thead><tr><th>Provider week/date</th><th>Boundary</th><th>Historical limit MW</th><th>Forecast limit MW</th></tr></thead><tbody>{(source?.records||[]).slice().sort((a,b)=>String(a.Date).localeCompare(String(b.Date))).flatMap(r=>Object.keys(r).filter(k=>k.endsWith(' - Forecast')).map(k=>{const name=k.replace(' - Forecast','');return <tr key={String(r.Date)+name}><th>{String(r.Date)}</th><td>{name}</td><td>{display(r[name+' - Actual'])}</td><td>{display(r[k])}</td></tr>}))}</tbody></table></div>{!source?.records.length&&<p>Published boundary limits unavailable.</p>}</section>}
 {tab==='costs'&&<section><p className="evidence-badge">RETROSPECTIVE · GBP</p><h2>Historical thermal constraint costs</h2><p>Latest reported day: <strong>{latestCost||'Unavailable'}</strong>. These are published daily outturn costs for significant boundary groups—not today’s bill, not a forecast and not a complete GB total.</p><div className="evidence-scroll"><table><thead><tr><th>Constraint group</th><th>Reported daily cost (£)</th></tr></thead><tbody>{costs.map(r=><tr key={String(r['Constraint Group'])}><th>{String(r['Constraint Group'])}</th><td>{display(r['Daily Cost (GBP)'])}</td></tr>)}</tbody></table></div><p>Do not add overlapping boundaries or compare these costs to an asset’s unused capacity. No curtailed MWh are inferred.</p></section>}
 <Source source={source}/><section className="evidence-footnote"><h2>What this can—and cannot—explain</h2><p>Forecast flows, network limits and historical costs provide useful context. Without matching operational evidence, they do not establish why a particular station changed output. This release does not infer curtailment from spare capacity or from schedules versus measured generation.</p><p>Supported by National Energy SO Open Data. Licensed under the NESO Open Data Licence. No Omnia data is used.</p></section></main>
}
