import {useQuery} from '@tanstack/react-query';
import {notificationReading} from '@/lib/notificationFeed.mjs';
export function useAssetOperations(enabled=true){return useQuery({queryKey:['asset-operations'],enabled,queryFn:async()=>{
 try{const r=await fetch('/api/asset-operations');if(!r.ok)throw Error('Unavailable');const j=await r.json();if(j.schemaVersion!==2)throw Error('Invalid response');return j}
 catch{const r=await fetch('/data/asset-operations.json');if(!r.ok)throw Error('Unavailable');return {...await r.json(),error:'Current endpoint unavailable; retained dated snapshot shown.'}}
},staleTime:15000,refetchInterval:30000,retry:1});}
export function AssetOperations({asset}:{asset:any}){
 const query=useAssetOperations();const data=query.data,reading=notificationReading(asset,data);
 if(!(asset.installedCapacityMW>100))return null;
 const time=(s:string)=>new Date(s).toLocaleString('en-GB',{timeZone:'Europe/London',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
 return <section className="asset-operations" aria-label="Notified operational schedule"><span className="asset-kicker">SCHEDULED · NOT MEASURED</span><h4>Notified output · {reading.current?'current half-hour':'last available period'}</h4><strong>{reading.mw===null?'Unavailable':`${reading.mw.toLocaleString('en-GB',{maximumFractionDigits:0})} MW`}</strong><p>{data?.from?`${time(data.from)} – ${time(data.to)} UK · half-hour average`:'Schedule interval unavailable'}. {reading.current?'Current-period notification, not live telemetry.':'Past notification; not a current schedule.'}</p><p>Expected output notified to Elexon, before balancing instructions. Not measured production or evidence of curtailment.</p>{reading.mw===null&&<p>{reading.note||'No complete verified notification is available. Missing data is not zero.'}</p>}{(query.isError||data?.error)&&<p>Refresh unavailable. Any retained notification keeps its original period.</p>}<details><summary>Schedule coverage and source</summary><p>{reading.coverage} / {reading.total} matched generating units with a complete, unambiguous interval. All matched units are required for a total; auxiliary plant and separate demand units are excluded.</p><p>{reading.units.join(', ')}</p><p>Retrieved: {data?.checkedAt?time(data.checkedAt):'Unavailable'} UK. Row publication time not supplied.</p><p>{reading.note}</p><a href={data?.url||'https://bmrs.elexon.co.uk/physical-notifications'}>Elexon PN source ↗</a><p>{data?.attribution}</p><p className="asset-revision">Revision: {data?.revision||'Unavailable'}</p></details></section>
}
