import {useGridEvidence} from '@/hooks/useGridEvidence';
import {halfHours} from '@/lib/evidence/calculations.mjs';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Pause, Play, Activity, BarChart3, BatteryCharging, Cable, Compass, FileText, Globe2, Leaf, Radio, RefreshCw, Search, ShieldCheck, Wind, Zap } from 'lucide-react';
import { GridAtlas } from './GridAtlas';
import { useEnergyData } from '@/contexts/EnergyDataContext';
import { useHistoricalGeneration } from '@/hooks/useHistoricalGeneration';
import { useCarbonOutlook } from '@/hooks/useCarbonOutlook';
import { finite, fuelValue, RENEWABLE_FUELS, sourceState, supplyBalance, transfers } from '@/lib/gridMetrics.mjs';
const palette: Record<string,string> = {Wind:'#00d9bf',Solar:'#f5d45e',Nuclear:'#ac83ff',Gas:'#439cf5',Hydro:'#20c5ee',Biomass:'#92d375',Other:'#758ca2',Coal:'#b9bfc8'};
const gw = (v: number | null | undefined) => finite(v) ? (v! / 1000).toFixed(1) : '—';
function Trace({values, color='#00dcc5', label}: {values:(number|null)[]; color?:string; label:string}) {
 const valid=values.filter((v):v is number=>finite(v));
 if(valid.length<2) return <div className="cc-no-series">Comparable history unavailable</div>;
 const min=Math.min(...valid), max=Math.max(...valid), span=max-min||1;
 const points=values.map((v,i)=>finite(v)?`${i/(values.length-1)*300},${64-(v!-min)/span*54}`:null);
 const segments:string[][]=[];points.forEach(p=>{if(p===null){segments.push([]);}else{if(!segments.length)segments.push([]);segments.at(-1)!.push(p)}});
 return <svg className="cc-trace" viewBox="0 0 300 76" preserveAspectRatio="none" role="img" aria-label={label}>{segments.map((s,i)=><g key={i}><polygon points={`${s[0]?.split(',')[0]},76 ${s.join(' ')} ${s.at(-1)?.split(',')[0]},76`} fill={color} opacity=".08"/><polyline points={s.join(' ')} fill="none" stroke={color} strokeWidth="1.8" vectorEffect="non-scaling-stroke"/></g>)}</svg>
}
export { CommandNavigation } from "./CommandNavigation";
export function GridCommandCentre({data,history,carbon,now}: {data:ReturnType<typeof useEnergyData>['data'];history:ReturnType<typeof useHistoricalGeneration>;carbon:ReturnType<typeof useCarbonOutlook>;now:number}) {
 const [units,setUnits]=useState<'GW'|'%'>('GW');
 const evidence=useGridEvidence();const evidenceRows=halfHours(evidence.data?.sources.FUELHH?.records||[],evidence.data?.sources.INDO?.records||[],now);const current=evidenceRows.at(-1);
 const mix=(current?.generationMix||[]).filter(m=>finite(m.value)).sort((a,b)=>b.value-a.value);
 const total=current?.generationMW;const renewable=total&&finite(current?.renewableMW)?current!.renewableMW/total*100:null;
 const fresh=data?.dataFreshness?.sourceFreshness;const status=sourceState(current?.to,30,now);
 const demand=current?.demandMW;const flow={net:current?.netImportsMW??null};
 const rows=[...history.data].filter(r=>+new Date(r.timestamp)<=now).sort((a,b)=>+new Date(a.timestamp)-+new Date(b.timestamp));
 const series=(fuel:string)=>rows.map(r=>r.fuelMix.find(f=>f.fuelType===fuel)?.mw??null);
 const forecast=carbon.periods.filter(p=>Date.parse(p.from)>=now);
 let offset=0;const gradient=mix.map(m=>{const start=offset;offset+=total?m.value/total*100:0;return `${palette[m.name]||'#758ca2'} ${start}% ${offset}%`}).join(',');
 return <><section className="cc-heading"><div><p className="map-eyebrow">GREAT BRITAIN / ELECTRICITY ATLAS</p><h1>Britain’s electricity. <br/><em>Live, explained.</em></h1><p>Generation, connections and the grid. Explore the places behind the power.</p></div><div className="cc-summary"><span><i className={status.fresh?'atlas-dot':''}/>{status.label}</span><span><b>{gw(total)} GW</b> Generation</span><span><b>{finite(renewable)?renewable.toFixed(0):'—'}%</b> Renewable</span><span><b>{data?.carbonIntensity?.actual??'—'}</b> gCO₂/kWh</span></div></section>
 <div className="cc-grid">
 <aside className="cc-metrics atlas-now">
 <article className="cc-panel cc-metric"><h2><Zap/>National demand</h2><strong>{gw(demand)} <small>GW</small></strong><p>Elexon INDO · measured initial outturn</p><Trace values={evidenceRows.map(r=>r.demandMW)} label="Initial national demand from cached Elexon INDO"/><small>Same completed periods as the evidence briefing</small></article>
 <article className="cc-panel cc-metric"><h2><Wind/>Renewable generation</h2><strong>{gw(current?.renewableMW)} <small>GW</small></strong><p><em>{finite(renewable)?renewable.toFixed(1):'—'}%</em> of transmission-metered generation</p><Trace values={evidenceRows.map(r=>r.renewableMW)} label="Historical measured renewable generation"/><small>FUELHH · excludes embedded wind and solar estimates</small></article>
 <article className="cc-panel cc-metric"><h2><Leaf/>Carbon intensity</h2><strong>{data?.carbonIntensity?.actual??'—'} <small>gCO₂/kWh</small></strong><p>{sourceState(fresh?.carbon?.timestamp,30,now).label}</p><Trace values={forecast.map(p=>p.intensity.forecast)} label="Future carbon intensity forecast"/><small>Upcoming forecast · not observed history</small></article>
 <article className="cc-panel cc-metric"><h2><Cable/>Net transfers</h2><strong>{gw(finite(flow.net)?Math.abs(flow.net):null)} <small>GW</small></strong><p><em>{finite(flow.net)?flow.net>0?'Importing':flow.net<0?'Exporting':'Balanced':'Unavailable'}</em> · half-hourly imports minus exports</p><div className="cc-transfer-symbol">EUROPE <span>⇄</span> GREAT BRITAIN</div><small>{sourceState(current?.to,30,now).label}</small></article>
 </aside>
 <GridAtlas summary={<section className="map-energy-summary" aria-label="Electricity snapshot"><div className="map-total"><span>Transmission-metered generation</span><strong>{gw(total)} <small>GW</small></strong><small>{status.label} · {current?.to?new Date(current.to).toLocaleTimeString('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit'})+' UK':'Observation unavailable'}</small></div><div className="map-summary-reading"><span>National demand</span><strong>{gw(demand)} <small>GW</small></strong></div><div className="map-summary-reading"><span>Carbon intensity</span><strong>{data?.carbonIntensity?.actual??'—'} <small>gCO₂/kWh</small></strong><small>{sourceState(fresh?.carbon?.timestamp,30,now).label}</small></div><div className="map-mix-strip" aria-hidden="true">{mix.map(m=><i key={m.name} style={{width:total?m.value/total*100+'%':'0',background:palette[m.name]||'#758ca2'}}/>)}</div><div className="map-mix-legend">{mix.map(m=><span key={m.name}><i style={{background:palette[m.name]||'#758ca2'}}/>{m.name}<b>{total?(m.value/total*100).toFixed(0)+'%':'—'}</b></span>)}</div><p>Generation excludes embedded estimates, storage and imports. Carbon has its own observation time.</p></section>} flows={data?.interconnectors||[]} regions={carbon.regions} regionFrom={carbon.from} regionTo={carbon.to} flowTime={fresh?.interconnectors?.timestamp||undefined} now={now}/>
 <aside className="cc-right">
 <section className="cc-panel cc-links"><h2><Cable/>Border snapshot <Link to="/interconnectors">View all ↗</Link></h2><div className="cc-table-head"><span>Connection</span><span>GW</span><span>Direction</span></div>{(data?.interconnectors||[]).map(f=><Link to="/interconnectors" className="cc-flow-row" key={f.name}><span><i>{({France:'FR',Belgium:'BE',Netherlands:'NL',Norway:'NO',Denmark:'DK',Ireland:'IE','Northern Ireland':'NI'} as Record<string,string>)[f.country]||'↔'}</i>{f.name}</span><b>{finite(f.flow)?`${f.flow>0?'+':''}${gw(f.flow)}`:'—'}</b><small>{!finite(f.flow)||f.status==='unavailable'||f.status==='offline'?'Unavailable':f.flow>0?'Into GB':f.flow<0?'Out of GB':'Balanced'}</small></Link>)}<p className="cc-source">Country-level feed · separate from cable observations</p></section>
 <section className="cc-panel cc-price"><h2><BarChart3/>Market price <Link to="/wholesale-electricity-price">Details ↗</Link></h2><strong>{data?.marketIndexPrice?`£${data.marketIndexPrice.priceGBPPerMWh.toFixed(2)}`:'—'} <small>/MWh</small></strong><div className="cc-market-rule"/><p>Wholesale market index</p><small>{sourceState(data?.marketIndexPrice?.startTime,30,now).label} · not your retail tariff</small></section>
 <section className="cc-panel cc-brief"><h2><Activity/>System briefing</h2><p><i/> <span><b>{mix[0]?`${mix[0].name} leads the mix`:'Awaiting generation'}</b>{mix[0]?`${gw(mix[0].value)} GW in the latest reading.`:'No values inferred.'}</span></p><p><i/> <span><b>Every reading has a clock</b>Source intervals differ. Inspect timestamps below.</span></p><Link to="/methodology">Definitions & evidence ↗</Link></section>
 </aside>
 <div className="cc-bottom"><section className="cc-panel cc-generation atlas-generation"><h2><Zap/>Generation mix <span className="atlas-tabs">{(['GW','%'] as const).map(u=><button key={u} aria-pressed={units===u} onClick={()=>setUnits(u)}>{u}</button>)}</span></h2><div className="cc-mix-body"><div className="cc-donut" style={{background:total?`conic-gradient(${gradient})`:'#18333e'}}><div><strong>{gw(total)}</strong><span>GW TOTAL</span></div></div><div className="cc-fuels">{mix.map(m=><Link className="atlas-fuel" to="/explore" key={m.name}><span><i style={{background:palette[m.name]}}/>{m.name}</span><b>{units==='GW'?gw(m.value):total?(m.value/total*100).toFixed(1):'—'}<small>{units}</small></b></Link>)}</div></div><p className="cc-source">Transmission-metered generation · excludes embedded estimates, storage & imports</p></section>
 <section className="cc-panel cc-storage"><h2><BatteryCharging/>Pumped storage <Link to="/pumped-storage">Explore ↗</Link></h2><div className="cc-storage-body"><div className="cc-storage-gauge"><BatteryCharging/><strong>{gw(current?.storageMW)} <small>GW</small></strong><span>{'Signed metered output'}</span></div><div><Trace values={evidenceRows.map(r=>r.storageMW)} color="#ad87ff" label="Historical signed pumped-storage output"/><p>Measured output history</p><small>{sourceState(current?.to,30,now).label}</small></div></div><p className="cc-source">Signed FUELHH PS reading · negative values retained; not battery state of charge</p></section>
 <section className="cc-panel cc-carbon"><h2><Wind/>Carbon outlook <a href="#outlook">Find a window ↗</a></h2><Trace values={forecast.map(p=>p.intensity.forecast)} label="Upcoming carbon forecast in gCO₂ per kWh"/><div className="cc-chart-axis"><span>Next half-hour</span><span>Returned forecast horizon →</span></div><p className="cc-source">Carbon Intensity API · forecast, not a guarantee</p></section>
 </div></div></>;
}
