import {Link} from 'react-router-dom';
import {useGridEvidence} from '@/hooks/useGridEvidence';
import {changesEvidence,boundarySummary} from '@/lib/evidence/calculations.mjs';
import '@/styles/grid-evidence.css';
export const evidenceTime=(iso:string|null|undefined)=>iso?new Date(iso).toLocaleString('en-GB',{timeZone:'Europe/London',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Not supplied';
export function GridEvidenceBriefing(){
 const feed=useGridEvidence(),s=feed.data?.sources;const changes=changesEvidence(s?.FUELHH?.records||[],s?.INDO?.records||[]);const network=boundarySummary(s?.dayAhead?.records||[]);const above=network.filter(r=>r.gapMW!==null&&r.gapMW<0);
 return <section className="grid-evidence-brief" aria-label="Validated grid evidence"><header><div><p className="atlas-eyebrow">WHAT CHANGED / EVIDENCE FIRST</p><h2>The grid, explained in context.</h2></div><Link to="/network-constraints">Explore network constraints ↗</Link></header>
 {changes?<><p className="evidence-caption">Completed half-hours starting {evidenceTime(changes.before.from)} → {evidenceTime(changes.after.from)} UK. {changes.fresh?'Recent observations.':'Historical comparison — not a current trend.'} {(s?.FUELHH?.error||s?.INDO?.error||feed.isError)&&'Refresh failed; retained evidence is dated below.'}</p><div className="evidence-metrics">{changes.rows.filter(r=>['demandMW','windMW','gasMW','netImportsMW'].includes(r.key)).map(r=><article key={r.key}><span>{r.label}</span><strong>{r.delta===null?'Unavailable':`${r.delta>0?'+':''}${r.delta.toLocaleString('en-GB',{maximumFractionDigits:0})} MW`}</strong><small>Measured change · same half-hours</small></article>)}</div><p>These movements happened together. They do not establish why a generator changed output, or whether network constraints caused it.</p><details><summary>Definitions and supporting observations</summary><div className="evidence-scroll"><table><thead><tr><th>Measure</th><th>Earlier MW</th><th>Later MW</th><th>Change MW</th></tr></thead><tbody>{changes.rows.map(r=><tr key={r.key}><th>{r.label}</th><td>{r.before??'—'}</td><td>{r.after??'—'}</td><td>{r.delta??'—'}</td></tr>)}</tbody></table></div><p>Initial national demand (INDO) is not the embedded-enriched supply balance shown by legacy charts. FUELHH covers transmission-metered output; embedded wind and solar estimates are not added. Storage is separate, not renewable generation. Positive net imports mean flow into GB; Northern Ireland is across an interconnector. These scopes do not reconcile to a complete national energy balance.</p><p>Observation publication times: {changes.after.publicationTimes.map(evidenceTime).join(' · ')} UK.</p><a href={s?.FUELHH.url}>Elexon FUELHH source</a> · <a href={s?.INDO.url}>Elexon INDO source</a></details></>:<p role="status">Comparable completed half-hours are unavailable. Missing readings are not converted into trends.</p>}
 <aside><h3>What comes next: network context</h3><p>{network.length?`${network.length} published boundary groups have upcoming day-ahead periods. ${above.length} have at least one forecast flow above the corresponding published directional limit in the retrieved window.`:'No time-valid day-ahead boundary periods are available in the cached source.'} This is a separate forecast window, not measured congestion or an explanation of the earlier generation changes.</p><p>Unused capacity, a forecast exceedance, or a schedule/output difference is not a curtailment estimate.</p></aside>
 <small>Deterministic comparisons of official evidence. No generated causal claims. Source revisions are available in the network evidence view. Contains BMRS data © Elexon Limited copyright and database right 2026. Supported by National Energy SO Open Data.</small>
 </section>
}
