import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const rootDir = new URL('..', import.meta.url).pathname;
const distDir = join(rootDir, 'dist');
const shell = readFileSync(join(distDir, 'index.html'), 'utf8');
const generated = JSON.parse(readFileSync(join(rootDir, 'src/data/energyMixGenerated.json'), 'utf8'));
const snapshot = JSON.parse(readFileSync(join(rootDir, 'src/data/staticGridSnapshot.json'), 'utf8'));
const latestReport = generated.reports[0];

const pages = [
  ['/', 'UK Electricity Mix Live | GB Grid Demand, Carbon Intensity & Renewables', 'Live Great Britain electricity mix today: demand, generation, renewables, gas, wind, solar, nuclear, imports and carbon intensity from public grid data.', 'UK Electricity Mix Live', ['EnergyMix.info shows Great Britain’s live electricity mix today, including demand, wind, solar, gas, nuclear, imports, storage, hydro, biomass and carbon intensity.', 'Most live grid data covers Great Britain’s electricity system: England, Scotland and Wales. Northern Ireland is part of the UK but operates in a separate electricity market.', 'The dashboard updates from public electricity and carbon-intensity sources. The latest visible app view shows current demand, generation, carbon intensity, renewable share, gas share, wind, solar, nuclear, imports/exports and source freshness where available.', 'The live dashboard appears first for visitors using the app. This static summary keeps the page clear for search engines, answer engines and browsers without JavaScript.']],
  ['/about', 'About EnergyMix.info | UK Electricity Dashboard', 'EnergyMix.info explains Great Britain’s live electricity system in plain English using public grid, generation and carbon-intensity data.', 'About EnergyMix.info', ['EnergyMix.info helps people understand Britain’s electricity system in plain English.', 'The site covers live electricity generation by source, demand, carbon intensity, renewable generation, gas, nuclear, interconnectors, storage trends, reports and practical clean-electricity insights.', 'Grid data can lag, change or be revised. EnergyMix.info explains source limitations and links back to original public data sources where appropriate.']],
  ['/data', 'Energy Mix Data Sources & Methodology | Elexon, NESO, Carbon Intensity', 'How EnergyMix.info collects, cleans and displays UK/GB electricity data from public grid, balancing and carbon-intensity sources.', 'Data Sources & Methodology', ['EnergyMix.info uses public electricity and carbon-intensity datasets to explain Great Britain’s live electricity mix.', 'Key sources include Elexon BMRS and FUELINST for live generation, NESO data sources including historic GB generation mix context, the Carbon Intensity API for GB and regional carbon-intensity estimates and forecasts, Sheffield Solar PV Live for embedded solar estimates, and ENTSO-E or BMRS-derived fallbacks for interconnector context.', 'Fast generation feeds can refresh frequently, supporting datasets refresh on their own cadence, and settlement-period data may update around 30-minute boundaries. Source freshness should be read from the dashboard rather than inferred from page load time alone.', 'Known limitations: datasets differ in coverage, embedded generation can be estimated, interconnector carbon impact depends on neighbouring systems, storage conventions vary, and upstream data can lag or be revised.', 'Suggested citation: Energy Mix, UK electricity dashboard, https://energymix.info/. For methodology, cite https://energymix.info/data and the original upstream sources where their licence requires it.']],
  ['/methodology', 'Energy Mix Methodology | GB Electricity Sources and Limits', 'Methodology for EnergyMix.info: geographic coverage, public data sources, refresh cadence, fuel categories, limitations and carbon-intensity interpretation.', 'Methodology', ['EnergyMix.info uses public electricity and carbon-intensity data to explain Great Britain’s live electricity mix.', 'Most live grid data covers Great Britain: England, Scotland and Wales. Northern Ireland is part of the UK but operates in a separate electricity market.', 'Generation, demand, interconnector and carbon-intensity figures may update on different schedules. Some figures are estimates or settlement-period values rather than physical real-time measurements.', 'The site is intended as a clear public explanation and intelligence layer, not as billing-grade metering or an official system-operator publication.']],
  ['/newsletter', 'Energy Mix Newsletter | Weekly UK Electricity & Carbon Insights', 'Get a weekly summary of Britain’s electricity mix, renewables, gas, carbon intensity, records and grid trends.', 'Energy Mix Newsletter', ['The Energy Mix Weekly Brief is designed as a short, useful summary of Britain’s electricity mix: renewables, gas, wind, solar, carbon intensity, demand, records and clean-electricity windows.', 'The newsletter is for readers who want the story behind the grid without checking live dashboards every day.', 'Typical briefings will focus on five useful numbers, the cleanest and highest-carbon periods, notable records, one practical takeaway and links to the full report.']],
  ['/contact', 'Contact EnergyMix.info | Corrections, Press, Widgets and Data', 'Contact EnergyMix.info about corrections, press, partnerships, sponsorship, widgets, data access or newsletter enquiries.', 'Contact EnergyMix.info', ['Use the contact page for data corrections, press questions, sponsorship, widget/API interest, partnerships and general Energy Mix enquiries.', 'For methodology questions, include the page URL, timestamp and data source if relevant so the issue can be checked properly.']],
  ['/privacy', 'Privacy Policy | EnergyMix.info', 'Privacy policy for EnergyMix.info, covering analytics, cookies, newsletter data and contact enquiries.', 'Privacy Policy', ['EnergyMix.info may use analytics and measurement tools to understand site usage, improve pages and measure newsletter or partner-interest actions.', 'Newsletter data, if submitted, is used for the newsletter context described at signup and can be unsubscribed from using the provider’s unsubscribe route.', 'The privacy page explains analytics, cookies, contact data and user choices in more detail.']],
  ['/citation', 'How to Cite EnergyMix.info | UK Electricity Mix Data', 'Citation guidance for EnergyMix.info live dashboard, reports, methodology and public electricity data sources.', 'How to cite EnergyMix.info', ['Suggested citation: Energy Mix, UK electricity dashboard, https://energymix.info/, accessed on the relevant date.', 'For specific reports or historical summaries, cite the individual page URL and access date.', 'Please also cite original public data sources such as Elexon, NESO or the Carbon Intensity API where required by their licence terms.']],
  ['/insights', 'Energy Mix Insights | UK Grid Trends & Renewable Generation Analysis', 'Brief explainers and weekly insights from the Energy Mix dashboard — highlighting shifts in UK power generation and renewable share.', 'Energy Insights', ['Energy Mix insights turn live grid data into short, plain-English explainers and weekly context.', 'Use this section to follow changes in renewables, gas, carbon intensity, demand, interconnectors and practical clean-electricity windows.']],
  ['/uk-electricity-mix', 'UK Electricity Mix Today | Live GB Generation by Source', 'Live Great Britain electricity mix today: generation by source, demand, renewables, gas, wind, solar, nuclear, imports and carbon intensity.', 'UK Electricity Mix', ['The UK electricity mix is the blend of sources generating power at a given moment.', 'Main sources include wind, solar, gas, nuclear, biomass, hydro, storage, imports and other generation.', 'The build-time snapshot gives crawlers and non-JavaScript readers a source-backed summary while the browser dashboard refreshes live values from public grid and carbon-intensity feeds.']],
  ['/carbon-intensity', 'UK Carbon Intensity Today | Live Grid CO₂/kWh', 'Live UK carbon intensity today: current GB grid CO₂/kWh, why it changes, cleaner electricity windows and practical timing for flexible demand.', 'UK Carbon Intensity', ['Carbon intensity estimates how much carbon dioxide is associated with each unit of electricity used.', 'It is usually lower when wind, solar, nuclear and other low-carbon sources supply more of the grid.', 'EnergyMix.info now includes regional and postcode carbon-intensity checks using NESO’s Carbon Intensity API.']],
  ['/renewables', 'UK Renewable Electricity Live | Wind, Solar, Hydro and Biomass', 'Live and plain-English guide to renewable electricity in Great Britain, including wind, solar, hydro, biomass, records, variability and carbon impact.', 'UK Renewable Electricity', ['Renewable electricity is a major part of Britain’s grid, especially when wind output is strong or solar is producing through the middle of the day.', 'Renewable share rises when wind, solar, hydro and biomass make up more of generation.']],
  ['/cleanest-time-to-use-electricity', 'Cleanest Time to Use Electricity UK | EV Charging and Appliances', 'Learn when electricity is usually cleanest in Britain and how carbon intensity, wind, solar, demand and imports affect EV charging and flexible electricity use.', 'Cleanest Time to Use Electricity', ['The cleanest time to use electricity is the period when the grid has lower carbon intensity.', 'EnergyMix.info uses the carbon-intensity forecast to highlight the next lower-carbon window for flexible electricity use.', 'Windy overnight periods, sunny middays and lower-demand windows are often cleaner than still evening peaks.']],
  ['/gas-generation', 'UK Gas Power Generation Live | Why Gas Is High Today', 'Plain-English guide to gas power generation in Great Britain: why gas rises, how it backs up wind and solar, and what it means for carbon intensity.', 'UK Gas Generation', ['Gas generation is the flexible part of Britain’s electricity system.', 'It often rises when demand is high, wind is low, solar has faded or imports are not covering the gap.']],
  ['/nuclear-power', 'UK Nuclear Power Today | Live Nuclear Electricity Share', 'Guide to nuclear power in Britain’s electricity mix: live output, low-carbon baseload, outages and how nuclear differs from wind and solar.', 'UK Nuclear Power', ['Nuclear power is one of Britain’s steadier low-carbon electricity sources.', 'It provides a low-carbon foundation but can change during outages and maintenance.']],
  ['/interconnectors', 'UK Electricity Imports and Exports Live | Interconnector Flows', 'Explain Britain’s electricity interconnectors, imports, exports, country flows and carbon impact in plain English.', 'UK Electricity Interconnectors', ['Interconnectors are high-voltage links that move electricity between Britain and neighbouring countries.', 'They can import power into Britain or export British power abroad.']],
  ['/electricity-demand', 'UK Electricity Demand Live | GB Grid Demand Today', 'Track and understand Great Britain electricity demand, daily demand curves, evening peaks, seasonal changes and carbon-intensity impact.', 'UK Electricity Demand', ['Electricity demand is how much power homes, businesses and industry need at a given moment.', 'Demand usually rises in the morning, peaks in the early evening and changes with weather, daylight and season.']],
  ['/uk-electricity-generation-live', 'UK Electricity Generation Live | GB Generation by Source', 'Live Great Britain electricity generation by source today, including wind, solar, gas, nuclear, hydro, biomass, storage, demand and interconnectors.', 'UK Electricity Generation Live', ['EnergyMix.info tracks live Great Britain electricity generation by source and explains what the numbers mean in plain English.', 'This page is for people looking specifically for live electricity generation by source, with links back to the broader electricity mix, demand and carbon-intensity context.']],
  ['/today', 'UK Electricity Mix Today | Live GB Generation & Carbon Intensity', 'UK electricity mix today: live Great Britain generation, demand, renewable share, gas output, wind, solar, carbon intensity and source freshness.', 'UK Electricity Mix Today', ['A live daily landing page for Britain’s electricity mix, showing the latest available demand, generation, renewables, gas and carbon-intensity context.', `Latest settled context: ${generated.yesterday.summary}`, 'Live values can move before settled daily reports are available, so this page pairs the browser-refreshed dashboard with generated source-backed daily context.']],
  ['/power-flow', 'GB Power Flow Live | UK Electricity Generation and Demand Visualisation', 'Live GB power flow visualisation showing UK electricity generation sources, demand, imports, exports, low-carbon share and carbon intensity.', 'GB Power Flow', ['A simplified live view of how Great Britain’s electricity generation, transfers and demand fit together.', 'The animated app view uses live generation, demand and interconnector data. The static version keeps the page discoverable for search engines and browsers without JavaScript.']],
  ['/yesterday', `${generated.yesterday.title} | EnergyMix.info`, 'Yesterday’s Great Britain electricity mix summary: average generation, renewable share, wind, solar and gas output from available historical data.', generated.yesterday.title, [generated.yesterday.summary, generated.yesterday.metrics.map(([k, v]) => `${k}: ${v}`).join(' · ')]],
  ['/reports', 'UK Electricity Mix Reports | Weekly Grid Data Briefings', 'Weekly and daily UK electricity mix reports from EnergyMix.info: renewables, gas, wind, solar, demand, carbon intensity and clean electricity windows.', 'UK Electricity Mix Reports', ['A growing archive of plain-English reports on Britain’s electricity mix, carbon intensity, renewables, gas, demand and practical clean-electricity windows.', `Latest report: ${latestReport.title}. ${latestReport.summary}`, 'Reports are generated from the available historical generation feed and link back to the live dashboard and source notes so the public numbers can be checked.']],
  [latestReport.slug, `${latestReport.title} | EnergyMix.info`, 'Weekly EnergyMix.info report for Britain’s electricity mix, renewable share, gas generation, carbon intensity and practical clean-electricity takeaways.', latestReport.title, [latestReport.summary, latestReport.metrics.map(([k, v]) => `${k}: ${v}`).join(' · ')]],
  ['/records', 'UK Electricity Mix Records | Wind, Solar, Renewables and Gas', 'EnergyMix.info records hub for Britain’s electricity mix: renewable share, wind generation, solar generation, gas generation and future carbon-intensity records.', 'UK Electricity Mix Records', ['A records hub for notable British electricity mix moments: renewable share highs, wind and solar peaks, gas-heavy periods and future carbon-intensity records.', 'These first records use the available 7-day historical generation feed.']],
  ['/records/highest-renewable-share', 'Highest Renewable Share | UK Electricity Mix Records', 'EnergyMix.info record page for Britain’s highest renewable electricity share, with source notes and related live dashboard links.', 'Highest Renewable Share Record', [generated.records.highestRenewableShare.text, 'Renewable share records show when wind, solar and hydro materially reduce fossil generation.']],
  ['/records/highest-wind-generation', 'Highest Wind Generation | UK Electricity Mix Records', 'EnergyMix.info record page for Britain’s highest wind generation observations and wind-led electricity mix periods.', 'Highest Wind Generation Record', [generated.records.highestWindGeneration.text, 'Wind is often the largest swing factor in Britain’s electricity mix.']],
  ['/records/highest-solar-generation', 'Highest Solar Generation | UK Electricity Mix Records', 'EnergyMix.info record page for Britain’s strongest solar generation periods and solar contribution to the daily electricity mix.', 'Highest Solar Generation Record', [generated.records.highestSolarGeneration.text, 'Solar reshapes the daytime grid and often lowers gas demand through the middle of bright days.']],
  ['/records/highest-gas-generation', 'Highest Gas Generation | UK Electricity Mix Records', 'EnergyMix.info record page for high gas generation periods, demand peaks and carbon-intensive electricity mix conditions.', 'Highest Gas Generation Record', [generated.records.highestGasGeneration.text, 'Gas highs show when the system is leaning more heavily on flexible fossil generation.']],
  ['/social', 'Energy Mix LinkedIn Post Templates | Weekly Grid Briefs', 'Ready-to-use LinkedIn post templates for EnergyMix.info weekly grid briefs, electricity explainers and clean-electricity updates.', 'LinkedIn post templates', generated.socialPosts.map((post) => `${post.title}: ${post.body}`)],
  ['/measurement', 'Energy Mix Measurement Plan | GA4, Search Console and SEO Tracking', 'Operational measurement plan for EnergyMix.info: Search Console, GA4, LinkedIn referrals, newsletter conversions and weekly reporting checks.', 'Measurement plan', ['Track Search Console clicks, impressions, indexed pages and new query terms weekly.', 'Track GA4 active users, page views, returning users, top landing pages and newsletter conversion events.', 'Prioritise pages gaining impressions: cleanest-time, carbon-intensity, interconnectors, demand and data-source pages.']],
  ['/glossary', 'UK Electricity Glossary | Energy Mix Terms Explained', 'Plain-English glossary for UK electricity mix terms: carbon intensity, FUELINST, interconnectors, renewable share, settlement periods and demand.', 'UK electricity glossary', ['A compact guide to the terms used across Energy Mix, built for readers who want the picture quickly without turning the dashboard into a textbook.', 'Definitions include carbon intensity, electricity mix, FUELINST, interconnectors, renewable share, settlement periods and system demand.']],
  ['/partners', 'Energy Mix for Publishers, Widgets and Data Access', 'Register interest in Energy Mix widgets, live GB electricity summaries, publisher explainers and future data access pilots.', 'Energy Mix widgets and data access', ['A quiet landing page for the commercial layer: simple live grid summaries, embeddable cards and useful data access without crowding the public dashboard.', 'Potential formats include embeddable power-flow cards, weekly briefings and selected lightweight live summaries for partners.']]
];

const nav = '<p><a href="/">Live dashboard</a> · <a href="/uk-electricity-mix">UK electricity mix</a> · <a href="/carbon-intensity">Carbon intensity</a> · <a href="/renewables">Renewables</a> · <a href="/cleanest-time-to-use-electricity">Cleanest time</a> · <a href="/gas-generation">Gas</a> · <a href="/interconnectors">Interconnectors</a> · <a href="/electricity-demand">Demand</a> · <a href="/uk-electricity-generation-live">Generation live</a> · <a href="/today">Today</a> · <a href="/power-flow">Power flow</a> · <a href="/reports">Reports</a> · <a href="/records">Records</a> · <a href="/glossary">Glossary</a> · <a href="/partners">Widgets and data</a></p>';

const schemaTag = (schema) => `<script type="application/ld+json">${JSON.stringify(schema)}</script>`;

const schemasFor = (route, title, description, canonical) => {
  const organization = { '@context': 'https://schema.org', '@type': 'Organization', name: 'EnergyMix.info', url: 'https://energymix.info/' };
  if (route === '/') {
    return schemaTag({ '@context': 'https://schema.org', '@type': 'WebSite', name: 'EnergyMix.info', url: 'https://energymix.info/', description }) + schemaTag(organization);
  }
  if (route === '/data' || route === '/methodology') {
    return schemaTag({ '@context': 'https://schema.org', '@type': 'Dataset', name: 'EnergyMix.info UK Electricity Mix Data', description: 'Live and recent electricity mix, demand, interconnector and carbon-intensity summaries for Great Britain, based on public electricity data sources.', url: canonical, creator: { '@type': 'Organization', name: 'EnergyMix.info', url: 'https://energymix.info/' }, spatialCoverage: { '@type': 'Place', name: 'Great Britain' }, isAccessibleForFree: true, keywords: ['Great Britain electricity mix', 'Elexon BMRS', 'FUELINST', 'NESO', 'Carbon Intensity API'] });
  }
  if (route.startsWith('/reports/weekly/')) {
    return schemaTag({ '@context': 'https://schema.org', '@type': 'Article', headline: title.replace(' | EnergyMix.info', ''), datePublished: latestReport.date, dateModified: latestReport.date, author: { '@type': 'Organization', name: 'EnergyMix.info' }, publisher: { '@type': 'Organization', name: 'EnergyMix.info', url: 'https://energymix.info/' }, mainEntityOfPage: canonical, description });
  }
  return schemaTag({ '@context': 'https://schema.org', '@type': 'WebPage', name: title, description, url: canonical, isPartOf: { '@type': 'WebSite', name: 'EnergyMix.info', url: 'https://energymix.info/' } });
};

const snapshotHtml = (() => {
  const d = snapshot.display || {};
  const asOf = snapshot.timestamp ? new Date(snapshot.timestamp).toISOString().replace('T', ' ').replace('.000Z', ' UTC') : 'latest available build-time snapshot';
  return `<section id="static-grid-snapshot"><h2>Latest GB electricity snapshot</h2><p>Snapshot timestamp: ${asOf}. Source freshness: ${snapshot.source || 'public grid data'} (${snapshot.status || 'latest available'}).</p><ul><li>Demand: ${d.demand || 'unavailable'}</li><li>Visible generation: ${d.generation || 'unavailable'}</li><li>Carbon intensity: ${d.carbonIntensity || 'unavailable'} (${d.carbonIndex || 'latest estimate'})</li><li>Renewable share: ${d.renewableShare || 'unavailable'}</li><li>Gas share: ${d.gasShare || 'unavailable'}</li><li>Wind: ${d.wind || 'unavailable'}</li><li>Solar: ${d.solar || 'unavailable'}</li><li>Nuclear: ${d.nuclear || 'unavailable'}</li><li>Imports/exports: ${d.importsExports || 'unavailable'}</li></ul><p>These values are a cached build-time snapshot for crawlers and non-JavaScript readers. The live dashboard refreshes in the browser from public grid and carbon-intensity sources.</p></section>`;
})();

for (const [route, title, description, h1, paragraphs] of pages) {
  const canonicalPath = route === '/' ? '/' : route === '/uk-electricity-mix' ? route : `${route}/`;
  const canonical = `https://energymix.info${canonicalPath}`;
  const includeSnapshot = ['/', '/uk-electricity-mix', '/carbon-intensity', '/renewables', '/gas-generation', '/nuclear-power', '/interconnectors', '/electricity-demand', '/uk-electricity-generation-live', '/cleanest-time-to-use-electricity', '/today', '/power-flow'].includes(route);
  const content = `<main id="seo-prerender"><h1>${h1}</h1>${includeSnapshot ? snapshotHtml : ''}${paragraphs.map((p) => `<p>${p}</p>`).join('')}${nav}</main>`;
  let html = shell
    .replace(/<title>[^<]*<\/title>/, `<title>${title}</title>`)
    .replace(/<meta name="description" content="[^"]*" \/>/, `<meta name="description" content="${description}" />`)
    .replace(/<link rel="canonical" href="[^"]*" \/>/, `<link rel="canonical" href="${canonical}" />`)
    .replace('</head>', `    ${schemasFor(route, title, description, canonical)}\n  </head>`)
    .replace(/<div id="root">[\s\S]*?<\/div>\s*<\/body>/, `<div id="root">${content}</div>\n  </body>`);
  if (route === '/social' || route === '/measurement') {
    html = html.replace('</head>', '    <meta name="robots" content="noindex, follow" />\n  </head>');
  }
  const out = route === '/' ? join(distDir, 'index.html') : join(distDir, route.slice(1), 'index.html');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, html);
}

console.log(`Prerendered ${pages.length} static HTML routes`);
