import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const rootDir = new URL('..', import.meta.url).pathname;
const distDir = join(rootDir, 'dist');
const shell = readFileSync(join(distDir, 'index.html'), 'utf8');
const generated = JSON.parse(readFileSync(join(rootDir, 'src/data/energyMixGenerated.json'), 'utf8'));
const snapshot = JSON.parse(readFileSync(join(rootDir, 'src/data/staticGridSnapshot.json'), 'utf8'));
const latestReport = generated.reports[0];

const pages = [
  ['/', 'UK Electricity Mix Live | EnergyMix.info', 'See Britain’s live electricity mix, demand, renewables, gas, imports, storage and carbon intensity in one plain-English dashboard.', 'UK Electricity Mix Live', ['EnergyMix.info shows what is powering Great Britain now: live electricity demand, generation by source, renewable share, gas, imports, storage and carbon intensity.', 'Use the dashboard to check wind, solar, gas, nuclear, storage, imports, exports and cleaner electricity windows in plain English.', 'Most live grid data covers Great Britain’s electricity system: England, Scotland and Wales. Northern Ireland is part of the UK but operates in a separate electricity market.', 'The live dashboard appears first for visitors using the app. This static summary keeps the page clear for search engines, answer engines and browsers without JavaScript.']],
  ['/about', 'About EnergyMix.info | UK Electricity Dashboard', 'EnergyMix.info explains Great Britain’s live electricity system in plain English using public grid, generation and carbon-intensity data.', 'About EnergyMix.info', ['EnergyMix.info helps people understand Britain’s electricity system in plain English.', 'The site covers live electricity generation by source, demand, carbon intensity, renewable generation, gas, nuclear, interconnectors, storage trends, reports and practical clean-electricity insights.', 'Grid data can lag, change or be revised. EnergyMix.info explains source limitations and links back to original public data sources where appropriate.']],
  ['/data', 'UK Electricity Data Sources: Elexon, NESO, Carbon Intensity & PV Live', 'How EnergyMix.info combines public electricity data sources to explain Britain’s live power mix, carbon intensity, solar estimates and grid trends.', 'UK Electricity Data Sources', ['EnergyMix.info combines public electricity and carbon-intensity data sources to explain Britain’s live power mix in plain English.', 'This page sets out what each source is used for, why figures can differ between dashboards, and where the important limitations are.', 'Key sources include Elexon BMRS and FUELINST for live generation, NESO data sources including historic GB generation mix context, the Carbon Intensity API for GB and regional carbon-intensity estimates and forecasts, Sheffield Solar PV Live for embedded solar estimates, and ENTSO-E or BMRS-derived fallbacks for interconnector context.', 'Known limitations: datasets differ in coverage, embedded generation can be estimated, interconnector carbon impact depends on neighbouring systems, storage conventions vary, and upstream data can lag or be revised.']],
  ['/methodology', 'Energy Mix Methodology | GB Electricity Sources and Limits', 'Methodology for EnergyMix.info: geographic coverage, public data sources, refresh cadence, fuel categories, limitations and carbon-intensity interpretation.', 'Methodology', ['EnergyMix.info uses public electricity and carbon-intensity data to explain Great Britain’s live electricity mix.', 'Most live grid data covers Great Britain: England, Scotland and Wales. Northern Ireland is part of the UK but operates in a separate electricity market.', 'Generation, demand, interconnector and carbon-intensity figures may update on different schedules. Some figures are estimates or settlement-period values rather than physical real-time measurements.', 'The site is intended as a clear public explanation and intelligence layer, not as billing-grade metering or an official system-operator publication.']],
  ['/newsletter', 'Weekly UK Electricity Mix Newsletter | EnergyMix.info', 'A short weekly brief on Britain’s electricity mix: renewables, gas, carbon intensity, records and the cleanest times to use power.', 'Weekly UK Electricity Mix Newsletter', ['A short weekly brief on Britain’s electricity mix: renewables, gas, wind, solar, carbon intensity, demand, records and the cleanest periods to use power.', 'Each issue is drawn from the live dashboard, weekly reports and transparent data sources.', 'Typical briefings focus on useful numbers, notable records, one practical takeaway and links to the full report.']],
  ['/contact', 'Contact EnergyMix.info | Corrections, Press, Widgets and Data', 'Contact EnergyMix.info about corrections, press, partnerships, sponsorship, widgets, data access or newsletter enquiries.', 'Contact EnergyMix.info', ['Use the contact page for data corrections, press questions, sponsorship, widget/API interest, partnerships and general Energy Mix enquiries.', 'For methodology questions, include the page URL, timestamp and data source if relevant so the issue can be checked properly.']],
  ['/privacy', 'Privacy Policy | EnergyMix.info', 'Privacy policy for EnergyMix.info, covering analytics, cookies, newsletter data and contact enquiries.', 'Privacy Policy', ['EnergyMix.info may use analytics and measurement tools to understand site usage, improve pages and measure newsletter or partner-interest actions.', 'Newsletter data, if submitted, is used for the newsletter context described at signup and can be unsubscribed from using the provider’s unsubscribe route.', 'The privacy page explains analytics, cookies, contact data and user choices in more detail.']],
  ['/citation', 'How to Cite EnergyMix.info | UK Electricity Mix Data', 'Citation guidance for EnergyMix.info live dashboard, reports, methodology and public electricity data sources.', 'How to cite EnergyMix.info', ['Suggested citation: Energy Mix, UK electricity dashboard, https://energymix.info/, accessed on the relevant date.', 'For specific reports or historical summaries, cite the individual page URL and access date.', 'Please also cite original public data sources such as Elexon, NESO or the Carbon Intensity API where required by their licence terms.']],
  ['/insights', 'Energy Mix Insights | UK Grid Trends & Renewable Generation Analysis', 'Brief explainers and weekly insights from the Energy Mix dashboard — highlighting shifts in UK power generation and renewable share.', 'Energy Insights', ['Energy Mix insights turn live grid data into short, plain-English explainers and weekly context.', 'Use this section to follow changes in renewables, gas, carbon intensity, demand, interconnectors and practical clean-electricity windows.']],
  ['/uk-electricity-mix', 'UK Electricity Mix: Live GB Generation by Source', 'Track Britain’s electricity mix by fuel source, including wind, solar, gas, nuclear, imports, storage and low-carbon generation.', 'UK Electricity Mix', ['The UK electricity mix is the blend of sources supplying power at a given moment.', 'EnergyMix.info focuses on live Great Britain electricity data and explains how wind, solar, gas, nuclear, imports, storage, demand and carbon intensity shape the grid today.', 'The page explains UK vs GB coverage, renewable vs low-carbon electricity, why the mix changes and how it affects carbon intensity.']],
  ['/carbon-intensity', 'UK Carbon Intensity Now | Live Grid CO2/kWh', 'Check UK carbon intensity now: live GB grid CO2/kWh, regional carbon intensity, cleaner electricity windows and why the grid is high or low carbon today.', 'UK Carbon Intensity Now', ['UK carbon intensity shows how much carbon is associated with each kilowatt-hour of electricity used.', 'EnergyMix.info puts the live GB grid CO2/kWh number beside generation, demand, regional forecasts and cleaner electricity windows so the figure is easy to act on.', 'Carbon intensity is lower when more electricity comes from wind, solar, nuclear, hydro or cleaner imports, and higher when gas or other fossil generation fills more of demand.', 'The regional carbon-intensity module uses the Carbon Intensity API for local and postcode-based estimates where available.']],
  ['/renewables', 'UK Renewable Electricity Live | Wind, Solar, Hydro and Biomass', 'Live and plain-English guide to renewable electricity in Great Britain, including wind, solar, hydro, biomass, records, variability and carbon impact.', 'UK Renewable Electricity', ['Renewable electricity is a major part of Britain’s grid, especially when wind output is strong or solar is producing through the middle of the day.', 'Renewable share rises when wind, solar, hydro and biomass make up more of generation.']],
  ['/cleanest-time-to-use-electricity', 'Cleanest Time to Use Electricity UK | EV Charging and Appliances', 'Learn when electricity is usually cleanest in Britain and how carbon intensity, wind, solar, demand and imports affect EV charging and flexible electricity use.', 'Cleanest Time to Use Electricity', ['The cleanest time to use electricity is the period when the grid has lower carbon intensity.', 'EnergyMix.info uses the carbon-intensity forecast to highlight the next lower-carbon window for flexible electricity use.', 'Windy overnight periods, sunny middays and lower-demand windows are often cleaner than still evening peaks.']],
  ['/gas-generation', 'UK Gas Power Generation Live | Why Gas Is High Today', 'Plain-English guide to gas power generation in Great Britain: why gas rises, how it backs up wind and solar, and what it means for carbon intensity.', 'UK Gas Generation', ['Gas generation is the flexible part of Britain’s electricity system.', 'It often rises when demand is high, wind is low, solar has faded or imports are not covering the gap.']],
  ['/nuclear-power', 'UK Nuclear Power Today | Live Nuclear Electricity Share', 'Guide to nuclear power in Britain’s electricity mix: live output, low-carbon baseload, outages and how nuclear differs from wind and solar.', 'UK Nuclear Power', ['Nuclear power is one of Britain’s steadier low-carbon electricity sources.', 'It provides a low-carbon foundation but can change during outages and maintenance.']],
  ['/interconnectors', 'UK Electricity Imports and Exports Live | Interconnector Flows', 'Explain Britain’s electricity interconnectors, imports, exports, country flows and carbon impact in plain English.', 'UK Electricity Interconnectors', ['Interconnectors are high-voltage links that move electricity between Britain and neighbouring countries.', 'They can import power into Britain or export British power abroad.']],
  ['/electricity-demand', 'UK Electricity Demand Live | GB Grid Demand Today', 'Track and understand Great Britain electricity demand, daily demand curves, evening peaks, seasonal changes and carbon-intensity impact.', 'UK Electricity Demand', ['Electricity demand is how much power homes, businesses and industry need at a given moment.', 'Demand usually rises in the morning, peaks in the early evening and changes with weather, daylight and season.']],
  ['/uk-electricity-generation-live', 'UK Electricity Generation Live | GB Generation by Source', 'Live Great Britain electricity generation by source today, including wind, solar, gas, nuclear, hydro, biomass, storage, demand and interconnectors.', 'UK Electricity Generation Live', ['EnergyMix.info tracks live Great Britain electricity generation by source and explains what the numbers mean in plain English.', 'This page is for people looking specifically for live electricity generation by source, with links back to the broader electricity mix, demand and carbon-intensity context.']],
  ['/uk-wind-power-today', 'UK Wind Power Today | Live GB Wind Generation', 'Track UK wind power today with current GB wind generation, renewable-share context and plain-English electricity mix analysis.', 'UK Wind Power Today', ['A durable landing page for checking how much wind power is contributing to Britain’s electricity mix today.', `Latest static snapshot: wind ${snapshot.display?.wind || 'unavailable'}, renewable share ${snapshot.display?.renewableShare || 'unavailable'}, gas ${snapshot.display?.gas || 'unavailable'} and carbon intensity ${snapshot.display?.carbonIntensity || 'unavailable'}.`, 'Wind is often the biggest swing source in the GB electricity mix. When wind output rises, renewable share tends to improve and gas generation can fall if demand and interconnector flows allow it.', `Recent report context: ${latestReport.highlights?.[0]?.value || latestReport.summary}`]],
  ['/uk-solar-power-today', 'UK Solar Power Today | Live GB Solar Generation', 'Track UK solar power today with current GB solar generation, renewable-share context and plain-English electricity mix analysis.', 'UK Solar Power Today', ['A durable landing page for checking how much solar power is contributing to Britain’s electricity mix today.', `Latest static snapshot: solar ${snapshot.display?.solar || 'unavailable'}, renewable share ${snapshot.display?.renewableShare || 'unavailable'}, demand ${snapshot.display?.demand || 'unavailable'} and carbon intensity ${snapshot.display?.carbonIntensity || 'unavailable'}.`, 'Solar output follows daylight, weather and the season. It is usually strongest around the middle of bright days and can be near zero overnight.', `Recent report context: ${latestReport.highlights?.[1]?.value || generated.yesterday.summary}`]],
  ['/gas-share-of-electricity', 'Gas Share of UK Electricity | Live GB Gas Generation', 'Check the current gas share of UK electricity generation and understand how gas affects carbon intensity in the GB electricity mix.', 'Gas Share of UK Electricity', ['A durable landing page for understanding how much of Britain’s electricity is currently coming from gas and why that matters for emissions.', `Latest static snapshot: gas share ${snapshot.display?.gasShare || 'unavailable'}, gas generation ${snapshot.display?.gas || 'unavailable'}, renewable share ${snapshot.display?.renewableShare || 'unavailable'} and carbon intensity ${snapshot.display?.carbonIntensity || 'unavailable'}.`, 'Gas-fired generation is flexible and often responds when demand is high, wind is low or other sources are unavailable. A higher gas share is usually a sign that the electricity mix is more carbon intensive.', `Recent report context: ${latestReport.highlights?.[2]?.value || latestReport.summary}`]],
  ['/renewables-share-today', 'Renewables Share Today | UK Electricity Mix', 'Check today’s renewable share of UK electricity generation, including wind and solar context for the live GB electricity mix.', 'Renewables Share Today', ['A durable landing page for today’s renewable electricity share, bringing together wind, solar, hydro and wider grid context.', `Latest static snapshot: renewable share ${snapshot.display?.renewableShare || 'unavailable'}, wind ${snapshot.display?.wind || 'unavailable'}, solar ${snapshot.display?.solar || 'unavailable'} and gas share ${snapshot.display?.gasShare || 'unavailable'}.`, 'Renewable share can change quickly as weather-driven generation moves and demand rises or falls.', `Recent report context: renewables averaged ${latestReport.metrics?.[1]?.[1] || 'the latest reported value'}, with ${latestReport.metrics?.[2]?.[1] || 'a recent renewable high'}.`]],
  ['/carbon-intensity-today', 'UK Carbon Intensity Today | Live GB Electricity Emissions', 'Check UK carbon intensity today with current GB electricity emissions context, renewable share, gas generation and demand.', 'UK Carbon Intensity Today', ['A durable landing page for today’s electricity carbon intensity in Great Britain, linking the live emissions signal to renewables, gas and demand.', `Latest static snapshot: carbon intensity ${snapshot.display?.carbonIntensity || 'unavailable'}, renewable share ${snapshot.display?.renewableShare || 'unavailable'}, gas share ${snapshot.display?.gasShare || 'unavailable'} and demand ${snapshot.display?.demand || 'unavailable'}.`, 'Electricity carbon intensity estimates the grams of CO2-equivalent emitted for each kilowatt-hour consumed. Lower values usually appear when wind, solar, nuclear and other low-carbon sources make up more of the mix.', latestReport.takeaway]],
  ['/today', 'UK Electricity Mix Today | Live Generation and Carbon Intensity', 'Today’s live GB electricity mix, renewable share, gas, demand and carbon intensity, explained in plain English.', 'UK Electricity Mix Today', ['A live daily landing page for Britain’s electricity mix, showing the latest available demand, generation, renewables, gas and carbon-intensity context.', `Latest settled context: ${generated.yesterday.summary}`, 'Live values can move before settled daily reports are available, so this page pairs the browser-refreshed dashboard with generated source-backed daily context.']],
  ['/power-flow', 'GB Power Flow Live | UK Electricity Generation and Demand Visualisation', 'Live GB power flow visualisation showing UK electricity generation sources, demand, imports, exports, low-carbon share and carbon intensity.', 'GB Power Flow', ['A simplified live view of how Great Britain’s electricity generation, transfers and demand fit together.', 'The animated app view uses live generation, demand and interconnector data. The static version keeps the page discoverable for search engines and browsers without JavaScript.']],
  ['/yesterday', `${generated.yesterday.title} | EnergyMix.info`, 'Yesterday’s Great Britain electricity mix summary: average generation, renewable share, wind, solar and gas output from available historical data.', generated.yesterday.title, [generated.yesterday.summary, generated.yesterday.metrics.map(([k, v]) => `${k}: ${v}`).join(' · ')]],
  ['/reports', 'UK Electricity Mix Reports: Daily and Weekly Grid Summaries', 'Read daily and weekly summaries of Britain’s electricity mix, renewable share, gas generation, demand and carbon intensity.', 'UK Electricity Mix Reports', ['A growing archive of plain-English reports on Britain’s electricity mix, carbon intensity, renewables, gas, demand and practical clean-electricity windows.', `Latest report: ${latestReport.title}. ${latestReport.summary}`, 'Reports are generated from the available historical generation feed and link back to the live dashboard and source notes so the public numbers can be checked.']],
  [latestReport.slug, `${latestReport.title} | EnergyMix.info`, 'Weekly EnergyMix.info report for Britain’s electricity mix, renewable share, gas generation, carbon intensity and practical clean-electricity takeaways.', latestReport.title, [latestReport.summary, latestReport.metrics.map(([k, v]) => `${k}: ${v}`).join(' · ')]],
  ['/records', 'UK Electricity Mix Records | Wind, Solar, Renewables and Gas', 'EnergyMix.info records hub for Britain’s electricity mix: renewable share, wind generation, solar generation, gas generation and future carbon-intensity records.', 'UK Electricity Mix Records', ['A records hub for notable British electricity mix moments: renewable share highs, wind and solar peaks, gas-heavy periods and future carbon-intensity records.', 'These first records use the available 7-day historical generation feed.']],
  ['/records/highest-renewable-share', 'Highest Renewable Share | UK Electricity Mix Records', 'EnergyMix.info record page for Britain’s highest renewable electricity share, with source notes and related live dashboard links.', 'Highest Renewable Share Record', [generated.records.highestRenewableShare.text, 'Renewable share records show when wind, solar and hydro materially reduce fossil generation.']],
  ['/records/highest-wind-generation', 'Highest Wind Generation | UK Electricity Mix Records', 'EnergyMix.info record page for Britain’s highest wind generation observations and wind-led electricity mix periods.', 'Highest Wind Generation Record', [generated.records.highestWindGeneration.text, 'Wind is often the largest swing factor in Britain’s electricity mix.']],
  ['/records/highest-solar-generation', 'Highest Solar Generation | UK Electricity Mix Records', 'EnergyMix.info record page for Britain’s strongest solar generation periods and solar contribution to the daily electricity mix.', 'Highest Solar Generation Record', [generated.records.highestSolarGeneration.text, 'Solar reshapes the daytime grid and often lowers gas demand through the middle of bright days.']],
  ['/records/highest-gas-generation', 'Highest Gas Generation | UK Electricity Mix Records', 'EnergyMix.info record page for high gas generation periods, demand peaks and carbon-intensive electricity mix conditions.', 'Highest Gas Generation Record', [generated.records.highestGasGeneration.text, 'Gas highs show when the system is leaning more heavily on flexible fossil generation.']],
  ['/social', 'Energy Mix LinkedIn Post Templates | Weekly Grid Briefs', 'Ready-to-use LinkedIn post templates for EnergyMix.info weekly grid briefs, electricity explainers and clean-electricity updates.', 'LinkedIn post templates', generated.socialPosts.map((post) => `${post.title}: ${post.body}`)],
  ['/measurement', 'Energy Mix Measurement Plan | GA4, Search Console and SEO Tracking', 'Operational measurement plan for EnergyMix.info: Search Console, GA4, LinkedIn referrals, newsletter conversions and weekly reporting checks.', 'Measurement plan', ['Track Search Console clicks, impressions, indexed pages and new query terms weekly.', 'Track GA4 active users, page views, returning users, top landing pages and newsletter conversion events.', 'Prioritise pages gaining impressions: cleanest-time, carbon-intensity, interconnectors, demand and data-source pages.']],
  ['/glossary', 'UK Electricity Glossary | Energy Mix Terms Explained', 'Plain-English glossary for UK electricity mix terms: carbon intensity, FUELINST, interconnectors, renewable share, settlement periods and demand.', 'UK electricity glossary', ['A compact guide to the terms used across Energy Mix, built for readers who want the picture quickly without turning the dashboard into a textbook.', 'Definitions include carbon intensity, electricity mix, FUELINST, interconnectors, renewable share, settlement periods and system demand.']],
  ['/partners', 'Energy Mix for Publishers, Widgets and Data Access', 'Register interest in Energy Mix widgets, live GB electricity summaries, publisher explainers and future data access pilots.', 'Energy Mix widgets and data access', ['A quiet landing page for the commercial layer: simple live grid summaries, embeddable cards and useful data access without crowding the public dashboard.', 'Potential formats include embeddable power-flow cards, weekly briefings and selected lightweight live summaries for partners.']]
];

const nav = '<p><a href="/">Live dashboard</a> · <a href="/uk-electricity-mix">UK electricity mix</a> · <a href="/carbon-intensity">Carbon intensity</a> · <a href="/renewables">Renewables</a> · <a href="/cleanest-time-to-use-electricity">Cleanest time</a> · <a href="/gas-generation">Gas</a> · <a href="/uk-wind-power-today">Wind today</a> · <a href="/uk-solar-power-today">Solar today</a> · <a href="/renewables-share-today">Renewables today</a> · <a href="/carbon-intensity-today">Carbon today</a> · <a href="/gas-share-of-electricity">Gas share</a> · <a href="/interconnectors">Interconnectors</a> · <a href="/electricity-demand">Demand</a> · <a href="/uk-electricity-generation-live">Generation live</a> · <a href="/today">Today</a> · <a href="/power-flow">Power flow</a> · <a href="/reports">Reports</a> · <a href="/records">Records</a> · <a href="/glossary">Glossary</a> · <a href="/partners">Widgets and data</a></p>';

const schemaTag = (schema) => `<script type="application/ld+json">${JSON.stringify(schema)}</script>`;

const schemasFor = (route, title, description, canonical) => {
  const organization = { '@context': 'https://schema.org', '@type': 'Organization', name: 'EnergyMix.info', url: 'https://energymix.info/' };
  if (route === '/') {
    return schemaTag({ '@context': 'https://schema.org', '@type': 'WebSite', name: 'EnergyMix.info', url: 'https://energymix.info/', description }) + schemaTag(organization);
  }
  if (route === '/data' || route === '/methodology') {
    return schemaTag({ '@context': 'https://schema.org', '@type': 'Dataset', name: 'EnergyMix.info UK Electricity Mix Data', description: 'Live and recent electricity mix, demand, interconnector and carbon-intensity summaries for Great Britain, based on public electricity data sources.', url: canonical, creator: { '@type': 'Organization', name: 'EnergyMix.info', url: 'https://energymix.info/' }, spatialCoverage: { '@type': 'Place', name: 'Great Britain' }, isAccessibleForFree: true, keywords: ['Great Britain electricity mix', 'Elexon BMRS', 'FUELINST', 'NESO', 'Carbon Intensity API'] });
  }
  if (route.startsWith('/reports/weekly/')) {
    return schemaTag({ '@context': 'https://schema.org', '@type': 'Article', headline: title.replace(' | EnergyMix.info', ''), datePublished: latestReport.date, dateModified: latestReport.date, author: { '@type': 'Organization', name: 'EnergyMix.info' }, publisher: { '@type': 'Organization', name: 'EnergyMix.info', url: 'https://energymix.info/' }, mainEntityOfPage: canonical, description });
  }
  return schemaTag({ '@context': 'https://schema.org', '@type': 'WebPage', name: title, description, url: canonical, isPartOf: { '@type': 'WebSite', name: 'EnergyMix.info', url: 'https://energymix.info/' } });
};

const snapshotHtml = (() => {
  const d = snapshot.display || {};
  const asOf = snapshot.timestamp ? new Date(snapshot.timestamp).toISOString().replace('T', ' ').replace('.000Z', ' UTC') : 'latest available build-time snapshot';
  return `<section id="static-grid-snapshot" data-nosnippet><h2>Latest GB electricity snapshot</h2><p>Snapshot timestamp: ${asOf}. Source freshness: ${snapshot.source || 'public grid data'} (${snapshot.status || 'latest available'}).</p><ul><li>Demand: ${d.demand || 'unavailable'}</li><li>Visible generation: ${d.generation || 'unavailable'}</li><li>Carbon intensity: ${d.carbonIntensity || 'unavailable'} (${d.carbonIndex || 'latest estimate'})</li><li>Renewable share: ${d.renewableShare || 'unavailable'}</li><li>Gas share: ${d.gasShare || 'unavailable'}</li><li>Wind: ${d.wind || 'unavailable'}</li><li>Solar: ${d.solar || 'unavailable'}</li><li>Nuclear: ${d.nuclear || 'unavailable'}</li><li>Imports/exports: ${d.importsExports || 'unavailable'}</li></ul><p>These values are a cached build-time snapshot for crawlers and non-JavaScript readers. The live dashboard refreshes in the browser from public grid and carbon-intensity sources.</p></section>`;
})();

for (const [route, title, description, h1, paragraphs] of pages) {
  const canonicalPath = route === '/' ? '/' : route === '/uk-electricity-mix' ? route : `${route}/`;
  const canonical = `https://energymix.info${canonicalPath}`;
  const includeSnapshot = ['/', '/uk-electricity-mix', '/carbon-intensity', '/renewables', '/gas-generation', '/nuclear-power', '/interconnectors', '/electricity-demand', '/uk-electricity-generation-live', '/cleanest-time-to-use-electricity', '/uk-wind-power-today', '/uk-solar-power-today', '/gas-share-of-electricity', '/renewables-share-today', '/carbon-intensity-today', '/today', '/power-flow'].includes(route);
  const intro = paragraphs.slice(0, 2).map((p) => `<p>${p}</p>`).join('');
  const remaining = paragraphs.slice(2).map((p) => `<p>${p}</p>`).join('');
  const content = `<main id="seo-prerender"><h1>${h1}</h1>${intro}${includeSnapshot ? snapshotHtml : ''}${remaining}${nav}</main>`;
  let html = shell
    .replace(/<title>[^<]*<\/title>/, `<title>${title}</title>`)
    .replace(/<meta name="description" content="[^"]*" \/>/, `<meta name="description" content="${description}" />`)
    .replace(/<link rel="canonical" href="[^"]*" \/>/, `<link rel="canonical" href="${canonical}" />`)
    .replace('</head>', `    ${schemasFor(route, title, description, canonical)}\n  </head>`)
    .replace(/<div id="root">[\s\S]*?<\/div>\s*<\/body>/, `<div id="root">${content}</div>\n  </body>`);
  if (route === '/social' || route === '/measurement') {
    html = html.replace('</head>', '    <meta name="robots" content="noindex, follow" />\n  </head>');
  }
  const out = route === '/' ? join(distDir, 'index.html') : join(distDir, route.slice(1), 'index.html');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, html);
}

console.log(`Prerendered ${pages.length} static HTML routes`);
