import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const rootDir = new URL('..', import.meta.url).pathname;
const distDir = join(rootDir, 'dist');
const shell = readFileSync(join(distDir, 'index.html'), 'utf8');
const generated = JSON.parse(readFileSync(join(rootDir, 'src/data/energyMixGenerated.json'), 'utf8'));
const latestReport = generated.reports[0];

const pages = [
  ['/', 'EnergyMix.info | UK Electricity Dashboard', 'Live Great Britain electricity mix: demand, generation, renewables, gas, nuclear, imports and carbon intensity, updated from public grid data.', 'About the UK electricity mix', ['EnergyMix.info shows Great Britain’s live electricity mix, including demand, wind, solar, gas, nuclear, imports, storage, hydro, biomass and carbon intensity.', 'Most live grid data covers Great Britain’s electricity system: England, Scotland and Wales. Northern Ireland is part of the UK but operates in a separate electricity market.', 'The live dashboard appears first for visitors using the app. This static summary keeps the page clear for search engines, answer engines and browsers without JavaScript.']],
  ['/uk-electricity-mix', 'UK Electricity Mix | Live GB Generation by Source', 'Plain-English guide to the UK electricity mix, covering Great Britain generation by source, demand, renewables, gas, nuclear, imports and carbon intensity.', 'UK Electricity Mix', ['The UK electricity mix is the blend of sources generating power at a given moment.', 'Main sources include wind, solar, gas, nuclear, biomass, hydro, storage, imports and other generation.']],
  ['/carbon-intensity', 'UK Carbon Intensity Live | Grid CO₂ and Clean Electricity Windows', 'Understand UK electricity carbon intensity, why it changes and how to use cleaner grid periods for EV charging, appliances, batteries and business load shifting.', 'UK Carbon Intensity', ['Carbon intensity estimates how much carbon dioxide is associated with each unit of electricity used.', 'It is usually lower when wind, solar, nuclear and other low-carbon sources supply more of the grid.', 'EnergyMix.info now includes regional and postcode carbon-intensity checks using NESO’s Carbon Intensity API.']],
  ['/renewables', 'UK Renewable Electricity Live | Wind, Solar, Hydro and Biomass', 'Live and plain-English guide to renewable electricity in Great Britain, including wind, solar, hydro, biomass, records, variability and carbon impact.', 'UK Renewable Electricity', ['Renewable electricity is a major part of Britain’s grid, especially when wind output is strong or solar is producing through the middle of the day.', 'Renewable share rises when wind, solar, hydro and biomass make up more of generation.']],
  ['/cleanest-time-to-use-electricity', 'Cleanest Time to Use Electricity UK | EV Charging and Appliances', 'Learn when electricity is usually cleanest in Britain and how carbon intensity, wind, solar, demand and imports affect EV charging and flexible electricity use.', 'Cleanest Time to Use Electricity', ['The cleanest time to use electricity is the period when the grid has lower carbon intensity.', 'EnergyMix.info uses the carbon-intensity forecast to highlight the next lower-carbon window for flexible electricity use.', 'Windy overnight periods, sunny middays and lower-demand windows are often cleaner than still evening peaks.']],
  ['/gas-generation', 'UK Gas Power Generation Live | Why Gas Is High Today', 'Plain-English guide to gas power generation in Great Britain: why gas rises, how it backs up wind and solar, and what it means for carbon intensity.', 'UK Gas Generation', ['Gas generation is the flexible part of Britain’s electricity system.', 'It often rises when demand is high, wind is low, solar has faded or imports are not covering the gap.']],
  ['/nuclear-power', 'UK Nuclear Power Today | Live Nuclear Electricity Share', 'Guide to nuclear power in Britain’s electricity mix: live output, low-carbon baseload, outages and how nuclear differs from wind and solar.', 'UK Nuclear Power', ['Nuclear power is one of Britain’s steadier low-carbon electricity sources.', 'It provides a low-carbon foundation but can change during outages and maintenance.']],
  ['/interconnectors', 'UK Electricity Imports and Exports Live | Interconnector Flows', 'Explain Britain’s electricity interconnectors, imports, exports, country flows and carbon impact in plain English.', 'UK Electricity Interconnectors', ['Interconnectors are high-voltage links that move electricity between Britain and neighbouring countries.', 'They can import power into Britain or export British power abroad.']],
  ['/electricity-demand', 'UK Electricity Demand Live | GB Grid Demand Today', 'Track and understand Great Britain electricity demand, daily demand curves, evening peaks, seasonal changes and carbon-intensity impact.', 'UK Electricity Demand', ['Electricity demand is how much power homes, businesses and industry need at a given moment.', 'Demand usually rises in the morning, peaks in the early evening and changes with weather, daylight and season.']],
  ['/uk-electricity-generation-live', 'UK Electricity Generation Live | GB Grid Dashboard by Source', 'Live Great Britain electricity generation by source, including wind, solar, gas, nuclear, hydro, biomass, storage and interconnectors.', 'UK Electricity Generation Live', ['EnergyMix.info tracks live Great Britain electricity generation by source and explains what the numbers mean in plain English.', 'This page is for people looking specifically for live electricity generation by source.']],
  ['/today', 'UK Electricity Mix Today | Live Generation, Demand & Carbon Intensity', 'Today’s Great Britain electricity mix: live generation, demand, renewable share, gas output, carbon intensity and source freshness from public grid data.', 'UK Electricity Mix Today', ['A live daily landing page for Britain’s electricity mix, showing the latest available demand, generation, renewables, gas and carbon-intensity context.', 'Future iterations will add highest renewable share today, lowest carbon intensity today, peak demand and cleanest window.']],
  ['/power-flow', 'GB Power Flow Live | UK Electricity Generation and Demand Visualisation', 'Live GB power flow visualisation showing UK electricity generation sources, demand, imports, exports, low-carbon share and carbon intensity.', 'GB Power Flow', ['A simplified live view of how Great Britain’s electricity generation, transfers and demand fit together.', 'The animated app view uses live generation, demand and interconnector data. The static version keeps the page discoverable for search engines and browsers without JavaScript.']],
  ['/yesterday', `${generated.yesterday.title} | EnergyMix.info`, 'Yesterday’s Great Britain electricity mix summary: average generation, renewable share, wind, solar and gas output from available historical data.', generated.yesterday.title, [generated.yesterday.summary, generated.yesterday.metrics.map(([k, v]) => `${k}: ${v}`).join(' · ')]],
  ['/reports', 'Energy Mix Reports | Weekly UK Electricity Mix Briefings', 'Weekly and daily EnergyMix.info reports on Britain’s electricity mix, renewables, gas, demand, carbon intensity and clean electricity windows.', 'Energy Mix Reports', ['A growing archive of plain-English reports on Britain’s electricity mix, carbon intensity, renewables, gas, demand and practical clean-electricity windows.', `Latest report: ${latestReport.title}. ${latestReport.summary}`]],
  [latestReport.slug, `${latestReport.title} | EnergyMix.info`, 'Weekly EnergyMix.info report for Britain’s electricity mix, renewable share, gas generation, carbon intensity and practical clean-electricity takeaways.', latestReport.title, [latestReport.summary, latestReport.metrics.map(([k, v]) => `${k}: ${v}`).join(' · ')]],
  ['/records', 'UK Electricity Mix Records | Wind, Solar, Renewables and Gas', 'EnergyMix.info records hub for Britain’s electricity mix: renewable share, wind generation, solar generation, gas generation and future carbon-intensity records.', 'UK Electricity Mix Records', ['A records hub for notable British electricity mix moments: renewable share highs, wind and solar peaks, gas-heavy periods and future carbon-intensity records.', 'These first records use the available 7-day historical generation feed.']],
  ['/records/highest-renewable-share', 'Highest Renewable Share | UK Electricity Mix Records', 'EnergyMix.info record page for Britain’s highest renewable electricity share, with source notes and related live dashboard links.', 'Highest Renewable Share Record', [generated.records.highestRenewableShare.text, 'Renewable share records show when wind, solar and hydro materially reduce fossil generation.']],
  ['/records/highest-wind-generation', 'Highest Wind Generation | UK Electricity Mix Records', 'EnergyMix.info record page for Britain’s highest wind generation observations and wind-led electricity mix periods.', 'Highest Wind Generation Record', [generated.records.highestWindGeneration.text, 'Wind is often the largest swing factor in Britain’s electricity mix.']],
  ['/records/highest-solar-generation', 'Highest Solar Generation | UK Electricity Mix Records', 'EnergyMix.info record page for Britain’s strongest solar generation periods and solar contribution to the daily electricity mix.', 'Highest Solar Generation Record', [generated.records.highestSolarGeneration.text, 'Solar reshapes the daytime grid and often lowers gas demand through the middle of bright days.']],
  ['/records/highest-gas-generation', 'Highest Gas Generation | UK Electricity Mix Records', 'EnergyMix.info record page for high gas generation periods, demand peaks and carbon-intensive electricity mix conditions.', 'Highest Gas Generation Record', [generated.records.highestGasGeneration.text, 'Gas highs show when the system is leaning more heavily on flexible fossil generation.']],
  ['/social', 'Energy Mix LinkedIn Post Templates | Weekly Grid Briefs', 'Ready-to-use LinkedIn post templates for EnergyMix.info weekly grid briefs, electricity explainers and clean-electricity updates.', 'LinkedIn post templates', generated.socialPosts.map((post) => `${post.title}: ${post.body}`)],
  ['/measurement', 'Energy Mix Measurement Plan | GA4, Search Console and SEO Tracking', 'Operational measurement plan for EnergyMix.info: Search Console, GA4, LinkedIn referrals, newsletter conversions and weekly reporting checks.', 'Measurement plan', ['Track Search Console clicks, impressions, indexed pages and new query terms weekly.', 'Track GA4 active users, page views, returning users, top landing pages and newsletter conversion events.', 'Prioritise pages gaining impressions: cleanest-time, carbon-intensity, interconnectors, demand and data-source pages.']]
];

const nav = '<p><a href="/">Live dashboard</a> · <a href="/uk-electricity-mix">UK electricity mix</a> · <a href="/carbon-intensity">Carbon intensity</a> · <a href="/renewables">Renewables</a> · <a href="/cleanest-time-to-use-electricity">Cleanest time</a> · <a href="/gas-generation">Gas</a> · <a href="/interconnectors">Interconnectors</a> · <a href="/electricity-demand">Demand</a> · <a href="/uk-electricity-generation-live">Generation live</a> · <a href="/today">Today</a> · <a href="/power-flow">Power flow</a> · <a href="/reports">Reports</a> · <a href="/records">Records</a></p>';

for (const [route, title, description, h1, paragraphs] of pages) {
  const canonical = `https://energymix.info${route === '/' ? '/' : route}`;
  const content = `<main id="seo-prerender"><h1>${h1}</h1>${paragraphs.map((p) => `<p>${p}</p>`).join('')}${nav}</main>`;
  let html = shell
    .replace(/<title>[^<]*<\/title>/, `<title>${title}</title>`)
    .replace(/<meta name="description" content="[^"]*" \/>/, `<meta name="description" content="${description}" />`)
    .replace(/<link rel="canonical" href="[^"]*" \/>/, `<link rel="canonical" href="${canonical}" />`)
    .replace(/<div id="root">[\s\S]*?<\/div>\s*<\/body>/, `<div id="root">${content}</div>\n  </body>`);
  if (route === '/social' || route === '/measurement') {
    html = html.replace('</head>', '    <meta name="robots" content="noindex, follow" />\n  </head>');
  }
  const out = route === '/' ? join(distDir, 'index.html') : join(distDir, `${route.slice(1)}.html`);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, html);
}

console.log(`Prerendered ${pages.length} static HTML routes`);
