// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxvjgpuytezomdlsayif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4dmpncHV5dGV6b21kbHNheWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjYwMDQsImV4cCI6MjA3MjE0MjAwNH0.cEnOyHqSeamIXVX4N3-nkuXerqLsEsSsRD1Iy3mo15o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});